---
/mission_tunnel:
  ros__parameters:
    init_pose:
      position:
        x: 2.2
        y: -1.8
        z: 0.0
      orientation:
        x: 0.0
        y: 0.0
        yaw: 90
    goal_pose:
      position:
        x: 0.2
        y: -0.3
        z: 0.0
      orientation:
        x: 0.0
        y: 0.0
        yaw: 180
